site:
  title: "Brenon Silvestre - Timeline"
  description: "Bem vindo a minha timeline pessoal"
personal:
  name: "Brenon Silvestre"
  avatar: "https://github.com/BrenonSAraujo.png"
  socialNetworks:
     github: "https://www.github.com/BrenonSAraujo"
